version: '3.4'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - /dockerdata/dockervol/nginx/data:/data
      - /dockerdata/dockervol/nginx/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - /dockerdata/dockervol/nginx/mysql:/var/lib/mysql
  
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /dockerdata:/var/syncthing
    #ports:
    #  - 8384:8384
    #  - 22000:22000/tcp
    #  - 22000:22000/udp
    restart: unless-stopped
    deploy:
      mode: global
    networks:
      - outside
      
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - SERVERURL=wireguard.sturmgraar.com #optional
      - SERVERPORT=51820 #optional
      - PEERS="Daniel-Lt","Daniel-NOTE20" #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.0.0.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /dockerdata/dockervol/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1      
 
networks:
  outside:
    external:
      name: "host"
