version: '3.4'
services:  
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
      - MEM_STARTUP=1024M #optional
    volumes:
      - /dockerdata/dockervol/unifi/:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.labels.powerful==true    
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "82:80/tcp"
    environment:
      TZ: 'America/Montreal'
      PUID: 1000
      PGID: 1000
      WEBPASSWORD: 'hasbE3n1'
    # Volumes store your data between container upgrades
    volumes:
      - /dockerdata/dockervol/pihole/pihole:/etc/pihole/
      - /dockerdata/dockervol/pihole/dnsmasq:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
