version: '3.4'
services:
  nginxapp:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "nginxdb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - /dockerdata/dockervol/nginx/data:/data
      - /dockerdata/dockervol/nginx/letsencrypt:/etc/letsencrypt
  nginxdb:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - /dockerdata/dockervol/nginx/mysql:/var/lib/mysql
      
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
      - MEM_STARTUP=1024M #optional
    volumes:
      - /dockerdata/dockervol/unifi/:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    
  
  syncthing:
    image: syncthing/syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /dockerdata:/var/syncthing
    #ports:
    #  - 8384:8384
    #  - 22000:22000/tcp
    #  - 22000:22000/udp
    restart: unless-stopped
    deploy:
      mode: global
    networks:
      - outside
  
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      -  /dockerdata/dockervol/mosquitto/data:/mosquitto/data
      -  /dockerdata/dockervol/mosquitto/logs:/mosquitto/logs
      -  /dockerdata/dockervol/mosquitto/config:/mosquitto/config
      
networks:
  outside:
    external:
      name: "host"
