version: "3.4"
services:
  zwavejs2mqtt:
    image: zwavejs/zwavejs2mqtt:latest
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - TZ=America/Toronto  # uncomment and edit to match you timezone if you want logs time and dates to match your timezone instead of UTC.
    volumes:
      - /data/gluster/zwave/store:/usr/src/app/store
      - /dev/zwave:/dev/ttyACM0
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server
    deploy:
       placement:
         constraints:
           - node.labels.zwave==true
           
  node-red:
    image: nodered/node-red:latest
    tty: true
    stop_signal: SIGINT
    environment:
      - TZ=America/Toronto  # uncomment and edit to match you timezone if you want logs time and dates to match your timezone instead of UTC.
    volumes:
      - /data/gluster/node-red:/data
    ports:
      - '1880:1880' # port for web interface
      
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest-dev
    environment:
      - TZ=America/Toronto
    volumes:
      - /data/gluster/zigbee:/app/data
      - /dev/zigbee-serial:/dev/ttyACM0
    ports:
      # Frontend port
      - 8080:8080
    deploy:
          placement:
            constraints:
              - node.labels.zigbee==true
