version: "3.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    environment:
      - PUID=1000
      - PGID=1000a
      - TZ=America/Toronto
    volumes:
      - /glustermnt/heimdall/:/config
    ports:
      - 8080:80
      - 8443:443
