version: "3.6"
services:
  plex:
    image: lscr.io/linuxserver/plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
      - TZ=America/Toronto
    volumes:
      - /data/bigdrive/plex:/config
      - /nfs/media/TV:/tv
      - /nfs/media/Movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/tautulli/:/config
      - /data/scripts:/scripts
      - /nfs/media/TV:/tv
      - /nfs/media/Movies:/movies
    ports:
      - 8181:8181
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/ombi/:/config
    ports:
      - 3579:3579
    restart: unless-stopped
   
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/radarr/:/config
      - /nfs/media/Movies/:/movies #optional
      - /data/bigdrive/nzbget/completed/Movies:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/sonarr/:/config
      - /nfs/media/TV/:/tv #optional
      - /data/bigdrive/nzbget/completed/Series:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
      
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/nzbget:/config
      - /data/bigdrive/nzbget:/downloads #optional
    ports:
      - 6790:6789
    restart: unless-stopped
