version: "3.4"
services:
  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - /dockerdata/dockervol/ombi/:/config
    ports:
      - 3579:3579
      
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /dockerdata/dockervol/radarr/:/config
      - /nfs/media/Movies/:/movies #optional
      - /nfs/diskstation/nzbget/complete:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /dockerdata/dockervol/sonarr/:/config
      - /nfs/media/TV/:/tv #optional
      - /nfs/diskstation/nzbget/complete:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped