version: "3.6"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/gluster/tautulli/:/config
      - /data/gluster/scripts:/scripts
      - /nfs/media/TV:/tv
      - /nfs/media/Movies:/movies
    ports:
      - 8181:8181
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /data/gluster/overseerr/:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - /data/gluster/ombi/:/config
    ports:
      - 3579:3579
    restart: unless-stopped
   
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/gluster/radarr/:/config
      - /nfs/media/Movies/:/movies #optional
      - /bigdrive/nzbget/completed/Movies:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/gluster/sonarr/:/config
      - /nfs/media/TV/:/tv #optional
      - /bigdrive/nzbget/completed/Series:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
      
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/gluster/nzbget:/config
      - /bigdrive/nzbget/:/downloads
      #- /nfs/diskstation/downloads/completed:/complete #optional
    ports:
      - 6790:6789
    restart: unless-stopped
 
volumes:
  synology_homes:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.0.0.5,rw"
      device: ":/volume2/homes/"
      
  nzbget_downloads:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.0.0.5,rw"
      device: ":/volume2/downloads/"
      
  plex_media_tv:
    driver: rclone
    driver_opts:
      remote: 'MediaU:/TV'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
      vfs-cache-max-size: 50G

  plex_media_movies:
    driver: rclone
    driver_opts:
      remote: 'MediaU:/Movies'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
      vfs-cache-max-size: 50G
