version: "3.4"
services:
  node-red:
    image: nodered/node-red
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /dockerdata/dockervol/node-red:/data
    ports:
      - 1880:1880
