version: "3.4"
services:
  radarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /dockerdata/dockervol/sonarr/:/config
      - /nfs/media/TV/:/tv #optional
      - /nfs/diskstation/nzbget/complete:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
