version: "3.4"
services:
  resiliosync:
    image: lscr.io/linuxserver/resilio-sync
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /resilio/config:/config
      - /resilio/downloads:/downloads
      - /dockerdata/:/sync
    deploy:
      mode: global
    networks:
       - outside
networks:
  outside:
    external:
      name: "host"
