version: '3.4'
services:
  zwavejs2mqtt:
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - TZ=America/Toronto  # uncomment and edit to match you timezone if you want logs time and dates to match your timezone instead of UTC.
    networks:
      - zwave
    volumes:
      - /dockerdata/dockervol/zwave/store:/usr/src/app/store
      - /dev/zwave:/dev/zwave
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server
    deploy:
       placement:
        constraints:
          - node.labels.zwave=="true"
networks:
  zwave:

