version: '3.4'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=1D44EBBB5C7CC3468DC598C157C72731
      - TZ=America/Toronto  # uncomment and edit to match you timezone if you want logs time and dates to match your timezone instead of UTC.
    networks:
      - pi-zwave
    deploy:
      placement:
          constraints:
            - "node.labels.zwave==true"
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - /dockerdata/dockervol/zwave/store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server
#volumes:
#  glusterzwave:
#    driver: glusterfs
#    name: "gv0/zwave/store"

networks:
  pi-zwave:
# volumes:
#   zwavejs2mqtt:
#     name: zwavejs2mqtt
